version: '3.10'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
        - db
        - redis
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_db

  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/var/lib/redis/data/
    

  worker:
    restart: always
    build: 
      context: ./app
    command: ["celery", "--workdir=./", "-A", "proj", "worker"]
    depends_on:
      - redis
  
  celery-beats:
    restart: always
    build: 
      context: ./app
    command: ["celery", "--workdir=./", "-A", "proj", "beat", "-l", "info"]
    depends_on:
      - redis
  
  
volumes:
  postgres_data:
  redis_data: